SELECT --/*%expand*/*,
       M_MAPART_WORLD.LAND_SIZE,
       M_MAPART_WORLD.WORLD_NAME,
       M_MAPART_WORLD.WORLD_UUID,
       M_MAPART_LAND.LAND_ID
FROM M_MAPART_WORLD
         LEFT OUTER JOIN M_MAPART_LAND
                         ON M_MAPART_WORLD.LAND_SIZE = M_MAPART_LAND.SIZE
WHERE LAND_SIZE = /* worldName */0
