SELECT M_MAPART_LAND.LAND_ID, OWNER_UUID, NAME, X, Z, HEIGHT, WIDTH, CREATED_DATE, STATUS, M_MAPART_LAND.VERSION_NO, COLLABORATOR_UUID --/*%expand*/*
    FROM M_MAPART_LAND
RIGHT INNER JOIN D_MAPART_LAND_COLLABORATOR
    ON M_MAPART_LAND.LAND_ID = D_MAPART_LAND_COLLABORATOR.LAND_ID
WHERE
    COLLABORATOR_UUID = /* collaborator */'00aaa0a0-000a-000a-00aa-00a0000a0a00'
