SELECT M_MAPART_LAND.LAND_ID, OWNER_UUID, NAME, X, Z, HEIGHT, WIDTH, CREATED_DATE, STATUS, M_MAPART_LAND.VERSION_NO, D_MAPART_LAND_COLLABORATOR.COLLABORATOR_UUID --/*%expand*/*
    FROM M_MAPART_LAND
LEFT OUTER JOIN D_MAPART_LAND_COLLABORATOR
    ON M_MAPART_LAND.LAND_ID = D_MAPART_LAND_COLLABORATOR.LAND_ID
WHERE
    M_MAPART_LAND.LAND_ID = /* landId */0
