name: ${NAME}
version: ${VERSION}
description: A plugin for mapart
author: Akazukin-Team
website: https://discord.gg/De8T2NS74X

depend:
  - AkazukinLibrary
  - WorldGuard
  - WorldEdit
softdepend:
  - FastAsyncWorldEdit
  - GrimAC
  - NoCheatPlus
  - Matrix
  - Towny

database: false

main: net.akazukin.mapart.MapartPlugin
api-version: 1.19

commands:
  mapart:
    description: Mapart command
    permission: akazukin.mapart.command.mapart
    permission-message: You do not have permission!
    usage: /<command> help

permissions:
  akazukin.mapart.command.mapart:
    description: Allows to use mapart command
    default: true
  akazukin.mapart.command.mapart.gui:
    description: Allows to use gui command child of mapart
    default: true
    children:
      akazukin.mapart.command.mapart: true

  akazukin.mapart.command.mapart.copyright:
    description: Allows to use copyright command child of mapart
    default: true
    children:
      akazukin.mapart.command.mapart: true

  akazukin.mapart.command.mapart.manage:
    description: Allows to use manage command child of mapart
    default: op
    children:
      akazukin.mapart.command.mapart: true

  akazukin.mapart.*:
    description: Wildcard permission
    default: op
    children:
      akazukin.mapart.command.mapart: true
      akazukin.mapart.command.mapart.gui: true
      akazukin.mapart.command.mapart.copyright: true
      akazukin.mapart.command.mapart.management: true
