thread: 100

world: mapart

limit:
  collaborator: 10
  borrow:
    default: 20
    max: 50

land:
  size:
    min: 1
    max: 4
  height: 150

cooltime:
  teleport: 10 #Seconds
  clean: 300 #Seconds
