SELECT M_MAPART_LAND.LAND_ID, SIZE, OWNER_UUID, NAME, X, Z, HEIGHT, WIDTH, CREATED_DATE, STATUS, COLLABORATOR_UUID
--/*%expand*/*
FROM M_MAPART_LAND
    LEFT OUTER JOIN D_MAPART_LAND_COLLABORATOR
ON M_MAPART_LAND.LAND_ID = D_MAPART_LAND_COLLABORATOR.LAND_ID